INSERT INTO BENEFICIO (NOME, DESCRICAO, VALOR, ATIVO,VERSION) VALUES('Beneficio A', 'Descrição A', 1000.00, TRUE,0);
INSERT INTO BENEFICIO (NOME, DESCRICAO, VALOR, ATIVO,VERSION) VALUES('Beneficio B', 'Descrição B', 500.00, TRUE,0);
