INSERT INTO BENEFICIO (ID,NOME, DESCRICAO, VALOR, ATIVO, VERSION) VALUES (1,'Beneficio A', 'Descricao A', 1000.00, TRUE, 0);

INSERT INTO BENEFICIO (ID,NOME, DESCRICAO, VALOR, ATIVO, VERSION) VALUES (2,'Beneficio B', 'Descricao B', 500.00, TRUE, 0);

INSERT INTO BENEFICIO (ID,NOME, DESCRICAO, VALOR, ATIVO, VERSION) VALUES (3,'Beneficio C', 'Descricao C', 200.00, FALSE, 0);